improve cleaning error handling
Change-Id: Ic98b5f520417ad3d0e9f1d77efa4f3ddfcdaa1eb

diff --git a/src/gdb/Makefile.in b/src/gdb/Makefile.in
--- a/src/gdb/Makefile.in
+++ b/src/gdb/Makefile.in
@@ -2011,14 +2011,17 @@ subdir_do: force
 	     if (cd ./$${i}; \
 	       $(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
 	       echo "'$@' succeeded for '$${i}'"; \
-	     else exit 1; fi; \
+	     else echo "gdb/Makefile: '$@' failed for '$${i}'" >&2; exit 1; fi; \
 	   else echo "at least one Makefile missing for '$${i}'"; fi; \
 	  else \
 	    if [ -f ./$${i}/Makefile ]; then \
 	      if (cd ./$${i}; \
 	        $(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
 	        echo "'$@' succeeded for '$${i}'"; \
-	      else exit 1; fi; \
+	      else \
+	        echo "gdb/Makefile: '$@' failed for '$${i}'" >&2; \
+	        exit 1; \
+	      fi; \
 	    else echo "no Makefile for '$${i}'"; fi; \
 	  fi; \
 	done
diff --git a/src/gdb/gdbserver/Makefile.in b/src/gdb/gdbserver/Makefile.in
--- a/src/gdb/gdbserver/Makefile.in
+++ b/src/gdb/gdbserver/Makefile.in
@@ -536,19 +536,34 @@ maintainer-clean realclean distclean: clean
 
 subdir_do: force
 	@for i in $(DODIRS); do \
-		case $${i} in \
-		$(REQUIRED_SUBDIRS)) \
-			if [ ! -f ./$${i}/Makefile ]; then \
-				echo "Missing $${i}/Makefile" >&2; \
-				exit 1; \
-			fi ;; \
-		esac ; \
-		if [ -f ./$${i}/Makefile ] ; then \
-			if (cd ./$${i}; \
-				$(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
-				echo "'$@' succeeded for '$${i}'"; \
-			else exit 1; fi; \
-		else echo "no Makefile for '$${i}'"; fi; \
+	  case $${i} in \
+	  $(REQUIRED_SUBDIRS)) \
+	    if [ ! -f ./$${i}/Makefile ]; then \
+	      echo "Missing $${i}/Makefile" >&2; \
+	      exit 1; \
+	    fi ;; \
+	  esac; \
+	  if [ "x$${i}" = "x../gnulib" -o "x$${i}" = "x../build-gnulib" ]; then \
+	    if [ -f ./$${i}/Makefile -a -f ./$${i}/import/Makefile ]; then \
+	      if (cd ./$${i}; \
+	        $(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
+	        echo "'$@' succeeded for '$${i}'"; \
+	      else \
+	        echo "gdbserver/Makefile: '$@' failed for '$${i}'" >&2; \
+	        exit 1; \
+	      fi; \
+	    else echo "at least one Makefile missing for '$${i}'"; fi; \
+	  else \
+	    if [ -f ./$${i}/Makefile ]; then \
+	      if (cd ./$${i}; \
+	        $(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
+	        echo "'$@' succeeded for '$${i}'"; \
+	      else \
+	        echo "gdbserver/Makefile: '$@' failed for '$${i}'" >&2; \
+	        exit 1; \
+	      fi; \
+	    else echo "no Makefile for '$${i}'"; fi; \
+	  fi; \
 	done
 
 STAGESTUFF=${OBS} ${TSOBS} ${NTSOBS} ${ADD_FILES} init.c init.o version.c \
diff --git a/src/gdb/gnulib/Makefile.in b/src/gdb/gnulib/Makefile.in
--- a/src/gdb/gnulib/Makefile.in
+++ b/src/gdb/gnulib/Makefile.in
@@ -1684,15 +1684,18 @@ subdir_do: force
 		case $${i} in \
 		$(REQUIRED_SUBDIRS)) \
 			if [ ! -f ./$${i}/Makefile ]; then \
-				echo "Missing $${i}/Makefile" >&2; \
-				exit 1; \
+			    echo "Missing $${i}/Makefile" >&2; \
+			    exit 1; \
 			fi ;; \
 		esac; \
 		if [ -f ./$${i}/Makefile ]; then \
 			if (cd ./$${i}; \
-				$(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
-				echo "'$@' succeeded for '$${i}'"; \
-			else exit 1; fi; \
+			    $(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
+			    echo "'$@' succeeded for '$${i}'"; \
+			else \
+			    echo "gnulib/Makefile: '$@' failed for '$${i}'" >&2; \
+			    exit 1; \
+			fi; \
 		else echo "no Makefile for '$${i}'"; fi; \
 	done
 
diff --git a/src/gdb/gnulib/Makefile_orig.in b/src/gdb/gnulib/Makefile_orig.in
--- a/src/gdb/gnulib/Makefile_orig.in
+++ b/src/gdb/gnulib/Makefile_orig.in
@@ -164,19 +164,22 @@ do-maintainer-clean:
 
 subdir_do: force
 	@for i in $(DODIRS); do \
-		case $${i} in \
-		$(REQUIRED_SUBDIRS)) \
-			if [ ! -f ./$${i}/Makefile ]; then \
-				echo "Missing $${i}/Makefile" >&2; \
-				exit 1; \
-			fi ;; \
-		esac; \
-		if [ -f ./$${i}/Makefile ]; then \
-			if (cd ./$${i}; \
-				$(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
-				echo "'$@' succeeded for '$${i}'"; \
-			else exit 1; fi; \
-		else echo "no Makefile for '$${i}'"; fi; \
+	    case $${i} in \
+	    $(REQUIRED_SUBDIRS)) \
+	        if [ ! -f ./$${i}/Makefile ]; then \
+	            echo "Missing $${i}/Makefile" >&2; \
+	            exit 1; \
+	        fi ;; \
+	    esac; \
+	    if [ -f ./$${i}/Makefile ]; then \
+	        if (cd ./$${i}; \
+	            $(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
+	            echo "'$@' succeeded for '$${i}'"; \
+	        else \
+	            echo "gnulib/Makefile_orig: '$@' failed for '$${i}'" >&2; \
+	            exit 1; \
+	        fi; \
+	    else echo "no Makefile for '$${i}'"; fi; \
 	done
 
 Makefile: Makefile.in config.status
