try to propagate archflags better for tcl & expect
for the purposes of running `make check`

Change-Id: I9587bf5a0e01841369e466276081657a4761ee95

diff --git a/src/expect/testsuite/Makefile.in b/src/expect/testsuite/Makefile.in
--- a/src/expect/testsuite/Makefile.in
+++ b/src/expect/testsuite/Makefile.in
@@ -1,3 +1,5 @@
+# Makefile for the expect testsuite
+
 VPATH = @srcdir@
 srcdir = @srcdir@
 prefix = @prefix@
@@ -14,16 +16,25 @@ targetdir = $(datadir)/$(target_alias)
 SHELL = /bin/sh
 
 CC = @CC@
+CFLAGS = @CFLAGS@
+LDFLAGS = @LDFLAGS@
 TCLHDIR = @TCLHDIR@
 
+BUILD_ARCHITECTURE = @BUILD_ARCHITECTURE@
+HOST_ARCHITECTURE = @HOST_ARCHITECTURE@
+TARGET_ARCHITECTURE = @TARGET_ARCHITECTURE@
+C_ARCHFLAGS = -arch $(HOST_ARCHITECTURE)
+
+XCFLAGS = ${CFLAGS} ${C_ARCHFLAGS}
+
 CC_FOR_TARGET = ` \
-  if [ -f $${rootme}../gcc/Makefile ] ; then \
+  if [ -f $${rootme}../gcc/Makefile ]; then \
     echo $${rootme}../gcc/xgcc -B$${rootme}../gcc/; \
   else \
-    if [ "$(host_canonical)" = "$(target_canonical)" ] ; then \
+    if [ "$(host_canonical)" = "$(target_canonical)" ]; then \
       echo $(CC); \
     else \
-      t='$(program_transform_name)'; echo gcc | sed -e '' $$t; \
+      t='$(program_transform_name)'; echo gcc | sed -e '' $${t}; \
     fi; \
   fi`
 
@@ -32,9 +43,9 @@ EXPECT = `if [ -f $${rootme}/expect ] ; \
 	else echo expect; fi`
 
 RUNTEST = ` \
-  if [ -f ${srcdir}/../../dejagnu/runtest ] ; then \
-    echo ${srcdir}/../../dejagnu/runtest ; \
-  else echo runtest ;  fi`
+  if [ -f ${srcdir}/../../dejagnu/runtest ]; then \
+    echo ${srcdir}/../../dejagnu/runtest; \
+  else echo runtest;  fi`
 RUNTESTFLAGS =
 
 all:
@@ -46,19 +57,26 @@ check:
 installcheck:
 .NOEXPORT:
 
-check:	exp_test site.exp
+check:	exp_test site.exp ../expect
 	rootme=`cd .. && pwd`; export rootme; \
 	EXPECT=${EXPECT}; export EXPECT; \
-	if [ -f ../expect ] ; then  \
-	   TCL_LIBRARY=`echo ${TCLHDIR} | sed -e 's/-I//' -e 's/generic//'`/library ; \
-	   export TCL_LIBRARY ; \
-	else true ; fi ; \
-	$(RUNTEST) $(RUNTESTFLAGS) --tool expect EXPECT=$$EXPECT --srcdir $(srcdir)
+	if [ -f ../expect ]; then  \
+	   TCL_LIBRARY=`echo ${TCLHDIR} | sed -e 's/-I//' -e 's/generic//'`/library; \
+	   export TCL_LIBRARY; \
+	else echo "../expect is missing" >&2; fi; \
+	$(RUNTEST) $(RUNTESTFLAGS) --tool expect EXPECT=$${EXPECT} --srcdir $(srcdir)
 
 install:
 uninstall: force
 
 exp_test.o: ${srcdir}/exp_test.c
+	${CC} -c ${XCFLAGS} ${srcdir}/exp_test.c
+
+exp_test: exp_test.o
+	${CC} -o $@ ${XCFLAGS} exp_test.o
+
+../expect:
+	cd .. && ${MAKE} expect
 
 site.exp: Makefile
 	@echo "Making a new config file..."
