bringing zlib up to modern standards
(WIP)

Change-Id: Ic8942d738db4965762b89cd6dab8b8c856ad4f0e

diff --git a/src/zlib/configure b/src/zlib/configure
--- a/src/zlib/configure
+++ b/src/zlib/configure
@@ -6506,9 +6506,12 @@ if test "${ARFLAGS}" = "-o"; then
         unset am_cv_ar_interface
         unset ARFLAGS
     fi
+elif test "x${ARFLAGS}" = "x--" || test "x${ARFLAGS}" = "x."; then
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: ARFLAGS are '${ARFLAGS}' (which might fail)" >&5
+printf "%s\n" "$as_me: WARNING: ARFLAGS are '${ARFLAGS}' (which might fail)" >&2;}
 fi
 if test "x${ac_cv_path_SED}" = "x"; then
-  test -z "${ac_cv_path_SED}"
+  test -z "${ac_cv_path_SED}" || unset ac_cv_path_SED
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for a sed that does not truncate output" >&5
 printf %s "checking for a sed that does not truncate output... " >&6; }
 if test ${ac_cv_path_SED+y}
@@ -6591,9 +6594,18 @@ if test -e ./config.cache; then
     echo "hacking ./config.cache"
     sed -i.bak -e "s|ac_cv_prog_AR|bad_AR|g" ./config.cache
     sed -i.bak -e "s|am_cv_ar_interface|bad_ar_interface|g" ./config.cache
+    sed -i.bak -e "s|lt_cv_ar_at_file|bad_ar_at_file|g" ./config.cache
     sed -i.bak -e "s|ac_cv_env_CPP_set|bad_CPP_status|g" ./config.cache
     sed -i.bak -e "s|ac_cv_env_CPP_value|bad_CPP|g" ./config.cache
     sed -i.bak -e "s|ac_cv_prog_CPP|bad_CPP|g" ./config.cache
+elif test -e `pwd`/config.cache; then
+    echo "hacking `pwd`/config.cache"
+    sed -i.bak -e "s|ac_cv_prog_AR|bad_AR|g" `pwd`/config.cache
+    sed -i.bak -e "s|am_cv_ar_interface|bad_ar_interface|g" `pwd`/config.cache
+    sed -i.bak -e "s|lt_cv_ar_at_file|bad_ar_at_file|g" `pwd`/config.cache
+    sed -i.bak -e "s|ac_cv_env_CPP_set|bad_CPP_status|g" `pwd`/config.cache
+    sed -i.bak -e "s|ac_cv_env_CPP_value|bad_CPP|g" `pwd`/config.cache
+    sed -i.bak -e "s|ac_cv_prog_CPP|bad_CPP|g" `pwd`/config.cache
 fi
 
   if test -n "$ac_tool_prefix"; then
@@ -6894,6 +6906,8 @@ else
 fi
 
   fi
+else
+  test -n "${AR}" && echo "AR set to '${AR}'"
 fi
 # By default we simply use the C compiler to build assembly code.
 
@@ -7031,7 +7045,7 @@ fi
 
 
 if test "x${ac_cv_prog_AWK}" = "x"; then
-  test -z "${ac_cv_prog_AWK}"
+  test -z "${ac_cv_prog_AWK}" || unset ac_cv_prog_AWK
   for ac_prog in gawk mawk nawk awk
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -8052,6 +8066,9 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 # libtool:
+if test -d conftest.dSYM; then
+  rm -rf conftest.dSYM 2>/dev/null || rmdir conftest.dSYM 2>/dev/null
+fi
 case `pwd` in
   *\ * | *\	*)
     { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Libtool does not cope well with whitespace in \`pwd\`" >&5
@@ -21813,7 +21830,7 @@ printf "%s\n" "no, using $LN_S" >&6; }
 fi
 
 if test "x${ac_cv_prog_make_make_set}" = "x"; then
-  test -z "${ac_cv_prog_make_make_set}"
+  test -z "${ac_cv_prog_make_make_set}" || unset ac_cv_prog_make_make_set
   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking whether ${MAKE-make} sets \$(MAKE)" >&5
 printf %s "checking whether ${MAKE-make} sets \$(MAKE)... " >&6; }
 set x ${MAKE-make}
@@ -24723,7 +24740,7 @@ save_CFLAGS="${CFLAGS}"
 for real_option in -Wall -Wextra -Wwrite-strings -Wpointer-arith \
 -Wfloat-conversion -Wstrict-prototypes -Wmissing-prototypes -Wimplicit \
 -Wnested-externs -Wmissing-parameter-type -Wabi -Wswitch -Wparentheses \
--Wzero-length-bounds -Wfatal-errors; do
+-Wold-style-definition -Wzero-length-bounds -Wfatal-errors; do
   # Do the check with the no- prefix removed since gcc silently accepts
   # any -Wno-* option on purpose:
   case ${real_option} in
