more tinkering, July 20, 2024
Change-Id: I9a799a93067d7f3d1606e8132051c300d940e517

diff --git a/src/dejagnu/contrib/bluegnu2.0.3/Makefile.in b/src/dejagnu/contrib/bluegnu2.0.3/Makefile.in
--- a/src/dejagnu/contrib/bluegnu2.0.3/Makefile.in
+++ b/src/dejagnu/contrib/bluegnu2.0.3/Makefile.in
@@ -39,6 +39,8 @@ INSTALL = @INSTALL@
 INSTALL_PROGRAM = @INSTALL_PROGRAM@
 INSTALL_DATA = @INSTALL_DATA@
 
+ACLOCAL_AMFLAGS = -I../../m4
+
 CC = @CC@
 CFLAGS = -ggdb -O1 -Wall -Wextra -pedantic -Wno-unused
 
@@ -130,14 +132,14 @@ install:
 
 subdir_do: force
 	@for i in $(SUBDIRS); do \
-	   echo "Making $(DO) in $${i}..."; \
+	   echo "$@ in `pwd`: Making $(DO) in $${i}..."; \
 	   if [ -d ./$${i} ]; then \
 	     if (rootme=`pwd`/; export rootme; \
 	       rootsrc=`cd $(srcdir); pwd`/; export rootsrc; \
 	       cd ./$${i}; \
 	       $(MAKE) $(FLAGS_TO_PASS) $(DO)); \
 	     then echo "Making $(DO) succeeded for subdir $${i}."; \
-	     else exit 1; fi; \
+	     else echo "Making $(DO) failed for $${i}!" >&2 && exit 1; fi; \
 	   else echo "$${i} is not an existing directory."; fi; \
 	done
 force:
diff --git a/src/dejagnu/contrib/bluegnu2.0.3/example/Makefile.in b/src/dejagnu/contrib/bluegnu2.0.3/example/Makefile.in
--- a/src/dejagnu/contrib/bluegnu2.0.3/example/Makefile.in
+++ b/src/dejagnu/contrib/bluegnu2.0.3/example/Makefile.in
@@ -65,14 +65,14 @@ check:	force
 
 subdir_do: force
 	@for i in $(SUBDIRS); do \
-	   echo "Making $(DO) in $${i}..."; \
+	   echo "$@ in `pwd`: Making $(DO) in $${i}..."; \
 	   if [ -d ./$${i} ]; then \
 	     if (rootme=`pwd`/; export rootme; \
 	       rootsrc=`cd $(srcdir); pwd`/; export rootsrc; \
 	       cd ./$${i}; \
 	       $(MAKE) $(FLAGS_TO_PASS) $(DO)); then \
-	       echo "$@ target in `pwd` for $${i}: It worked."; \
-	     else exit 1; fi; \
+	       echo "$@ target in `pwd` for $${i}: Making $(DO) worked."; \
+	     else echo "Making $(DO) failed for $${i}!" >&2 && exit 1; fi; \
 	   else echo "$${i} is not an existing directory."; fi; \
 	done
 force:
