update autotools stuff again
includes (what I hope is) a fix for #4

Change-Id: Ieae442566ccfdcbd5c19f711b72dad4d95c4e567

diff --git a/src/intl/Makefile.am b/src/intl/Makefile.am
--- a/src/intl/Makefile.am
+++ b/src/intl/Makefile.am
@@ -169,6 +169,7 @@ libintl.la: $(LTOBJECTS) $(OBJECTS)
 EXTRA_DIST += po/Makevars.in
 
 check: all @MAINT@ config.status
+	ls *.i || ls *.s || ls *.bc
 .PHONY: check
 
 # This installation goal is only used in GNU gettext. Packages which
@@ -263,7 +264,26 @@ localealias.lo relocatable.lo: relocatable.h
 plural-exp.o: plural-exp.h
 plural-exp.lo: plural-exp.h
 
-plural.c: plural.y @MAINT@ Makefile
+plural.c: plural.y @MAINT@@BISON3_NO@ Makefile
+plural.lo: plural.c
+	$(LIBTOOL) --tag=CC --mode=compile $(COMPILE) $<; \
+	if [[ $$? -eq 1 ]]; then \
+	  if test -d ../../.git && test -n "${GIT_BIN}" && test -x "${GIT_BIN}"; then \
+	    if test -n "`${GIT_BIN} status -s plural.c | grep M`"; then \
+	      echo "plural.c appears to have been changed; attempting to restore it..."; \
+	      ${GIT_BIN} restore $<; \
+	      $(LIBTOOL) --tag=CC --mode=compile $(COMPILE) $<; \
+            else \
+              echo "error: plural.c does NOT seem to have been changed, so therefore building it ought to succeed; dunno what happened here..." >&2; \
+	      exit 1; \
+	    fi; \
+	  else \
+	    echo "error: bison 3 may have been used to re-yacc plural.c; you may need to either restore the previous version, or try re-yaccing with bison 2 instead." >&2; \
+	    exit 1; \
+	  fi; \
+	else \
+	  echo "compilation returned code $$?"; \
+	fi
 
 tags-lowercase: TAGS-uppercase
 .PHONY: tags-lowercase
@@ -286,7 +306,7 @@ mostlyclean-local: @MAINT@ config.status
 .PHONY: mostlyclean-local
 
 clean-local: mostlyclean-local @MAINT@ config.status
-	rm -f $(AM_V_v) *.s *.i
+	rm -f $(AM_V_v) *.s *.i *.bc
 .PHONY: clean-local
 
 distclean-local: clean-local @MAINT@ config.status
diff --git a/src/intl/Makefile.in b/src/intl/Makefile.in
--- a/src/intl/Makefile.in
+++ b/src/intl/Makefile.in
@@ -322,7 +322,9 @@ EXEEXT = @EXEEXT@
 EXTRA_ANSIFICATION_FLAGS = @EXTRA_ANSIFICATION_FLAGS@
 EXTRA_YFLAGS_SEP = @EXTRA_YFLAGS_SEP@
 FGREP = @FGREP@
+FILECMD = @FILECMD@
 GETTEXT_MACRO_VERSION = @GETTEXT_MACRO_VERSION@
+GIT_BIN = @GIT_BIN@
 GLIBC2 = @GLIBC2@
 GLIBC21 = @GLIBC21@
 GMSGFMT = @GMSGFMT@
@@ -1168,6 +1170,7 @@ libintl.la: $(LTOBJECTS) $(OBJECTS)
 	cd ../po && $(MAKE) cat-id-tbl.o
 
 check: all @MAINT@ config.status
+	ls *.i || ls *.s || ls *.bc
 .PHONY: check
 
 # This installation goal is only used in GNU gettext. Packages which
@@ -1262,7 +1265,26 @@ localealias.lo relocatable.lo: relocatable.h
 plural-exp.o: plural-exp.h
 plural-exp.lo: plural-exp.h
 
-plural.c: plural.y @MAINT@ Makefile
+plural.c: plural.y @MAINT@@BISON3_NO@ Makefile
+plural.lo: plural.c
+	$(LIBTOOL) --tag=CC --mode=compile $(COMPILE) $<; \
+	if [[ $$? -eq 1 ]]; then \
+	  if test -d ../../.git && test -n "${GIT_BIN}" && test -x "${GIT_BIN}"; then \
+	    if test -n "`${GIT_BIN} status -s plural.c | grep M`"; then \
+	      echo "plural.c appears to have been changed; attempting to restore it..."; \
+	      ${GIT_BIN} restore $<; \
+	      $(LIBTOOL) --tag=CC --mode=compile $(COMPILE) $<; \
+            else \
+              echo "error: plural.c does NOT seem to have been changed, so therefore building it ought to succeed; dunno what happened here..." >&2; \
+	      exit 1; \
+	    fi; \
+	  else \
+	    echo "error: bison 3 may have been used to re-yacc plural.c; you may need to either restore the previous version, or try re-yaccing with bison 2 instead." >&2; \
+	    exit 1; \
+	  fi; \
+	else \
+	  echo "compilation returned code $$?"; \
+	fi
 
 tags-lowercase: TAGS-uppercase
 .PHONY: tags-lowercase
@@ -1285,7 +1307,7 @@ mostlyclean-local: @MAINT@ config.status
 .PHONY: mostlyclean-local
 
 clean-local: mostlyclean-local @MAINT@ config.status
-	rm -f $(AM_V_v) *.s *.i
+	rm -f $(AM_V_v) *.s *.i *.bc
 .PHONY: clean-local
 
 distclean-local: clean-local @MAINT@ config.status
