more of the same
Change-Id: I89e0affc9cdedd52125a00462c5804d81f399dbc

diff --git a/src/utils/spu/Makefile.in b/src/utils/spu/Makefile.in
--- a/src/utils/spu/Makefile.in
+++ b/src/utils/spu/Makefile.in
@@ -32,6 +32,10 @@ srcdir = @srcdir@
 
 AUTOCONF = autoconf
 
+M4 = @M4@
+M4_GNU = @M4_GNU@
+M4_DEBUGFILE = @M4_DEBUGFILE@
+
 CC = @CC@
 CLANG_ANALYZER = @CLANG_ANALYZER@
 CPP = @CPP@
@@ -129,10 +133,33 @@ check-local: config.h @MAINT@ all
 .PHONY: check-local
 
 Makefile: $(srcdir)/Makefile.in config.status
-	./config.status
+	if test -x "$(M4)"; then \
+	  export M4="$(M4)"; \
+	elif test -n "$(M4)"; then \
+	  echo "cannot set M4=$(M4), because something is wrong with it"; \
+	else \
+	  echo "something is wrong with M4; check on it"; \
+	fi; \
+	if test -n "$${CPP}" && test "x$${CPP}" != "x$${ac_cv_env_CPP_value}"; then unset CPP; fi; \
+	./config.status || (test -s $@ && touch $@)
 
 config.status: $(srcdir)/configure
-	./config.status --recheck
+	if test -x "$(M4)"; then \
+	  export M4="$(M4)"; \
+	elif test -n "$(M4)"; then \
+	  echo "cannot set M4=$(M4), because something is wrong with it"; \
+	else \
+	  echo "something is wrong with M4; check on it"; \
+	fi; \
+	if test -n "$${CPP}" && test "x$${CPP}" != "x$${ac_cv_env_CPP_value}"; then unset CPP; fi; \
+	./config.status --recheck || (test -x $@ && test -s $@ && touch $@)
 
 $(srcdir)/configure: $(srcdir)/configure.ac
-	cd $(srcdir) && $(AUTOCONF) --force
+	if test -x "$(M4)"; then \
+	  export M4="$(M4)"; \
+	elif test -n "$(M4)"; then \
+	  echo "cannot set M4=$(M4), because something is wrong with it"; \
+	else \
+	  echo "something is wrong with M4; check on it"; \
+	fi; \
+	cd $(srcdir) && ($(AUTOCONF) --force || (test -x $@ && touch $@))
