housekeeping
Change-Id: Ic63c06deecb38295998ca0c59c1311397a61ef90

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -8865,8 +8865,12 @@ printf "%s\n" "$as_me: Unset the APPLE_INTERNAL_DIR environment variable to avoi
     fi
 # building zlib from this level can mess it up; build it manually instead:
     if test -z "${AR}" -o -z "${ARFLAGS}" -o "${AR}" = "libtool" -o "${AR}" = "ar" -o "${ARFLAGS}" = "-o"; then
-      ## FIXME: come up with a proper fix instead?
-      noconfigdirs="${noconfigdirs} zlib"
+      if test "x${enable_static}" = "xyes" || test "x${build_old_libs}" = "xyes"; then
+        ## FIXME: come up with a proper fix instead?
+        noconfigdirs="${noconfigdirs} zlib"
+      else
+        echo "zlib should probably fine so long as we avoid building its minizip subdir statically"
+      fi
     fi
 # autogen support in this tree is still tentative, so disable if guile is
 # not also present:
@@ -8931,7 +8935,11 @@ fi
     fi
 # Also similar to Apple case above:
     if test -z "${AR}" -o -z "${ARFLAGS}" -o "${AR}" = "libtool" -o "${AR}" = "ar" -o "${ARFLAGS}" = "-o" -o -n "${PIC_FLAG}"; then
-      noconfigdirs="${noconfigdirs} zlib"
+      if test "x${enable_static}" = "xyes" || test "x${build_old_libs}" = "xyes"; then
+        noconfigdirs="${noconfigdirs} zlib"
+      else
+        echo "zlib should probably fine so long as we avoid building its minizip subdir statically"
+      fi
     fi
 # autogen support in this tree is still tentative, so disable if guile is
 # not also present:
@@ -18658,7 +18666,9 @@ fi
 done
 test -n "$CONFIGURED_LEX" || CONFIGURED_LEX="${MISSING} flex"
 
-for ac_prog in makeinfo
+if test "x${MISSING}" != "x"; then
+  test -n "${MISSING}"
+  for ac_prog in makeinfo gmakeinfo
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -18706,6 +18716,59 @@ fi
   test -n "$CONFIGURED_MAKEINFO" && break
 done
 test -n "$CONFIGURED_MAKEINFO" || CONFIGURED_MAKEINFO="${MISSING} makeinfo"
+
+else
+  test -z "${MISSING}"
+  for ac_prog in makeinfo gmakeinfo
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_prog_CONFIGURED_MAKEINFO+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e) if test -n "$CONFIGURED_MAKEINFO"; then
+  ac_cv_prog_CONFIGURED_MAKEINFO="$CONFIGURED_MAKEINFO" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_prog_CONFIGURED_MAKEINFO="$ac_prog"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi ;;
+esac
+fi
+CONFIGURED_MAKEINFO=$ac_cv_prog_CONFIGURED_MAKEINFO
+if test -n "$CONFIGURED_MAKEINFO"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $CONFIGURED_MAKEINFO" >&5
+printf "%s\n" "$CONFIGURED_MAKEINFO" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+
+  test -n "$CONFIGURED_MAKEINFO" && break
+done
+test -n "$CONFIGURED_MAKEINFO" || CONFIGURED_MAKEINFO="makeinfo"
+
+fi
 
 for ac_prog in flex lex
 do
@@ -19949,7 +20012,9 @@ case " ${build_configdirs} " in
   *" flex "*) FLEX='$$r/$(BUILD_SUBDIR)/flex/flex' ;;
 esac
 
-for ac_prog in makeinfo
+if test "x${MISSING}" != "x" && test "x${SHELL}" != "x"; then
+  test -n "${MISSING}" && test -n "${SHELL}" && echo "${MISSING} ought to use ${SHELL} for makeinfo" && export SHELL
+  for ac_prog in makeinfo gmakeinfo
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -19998,17 +20063,81 @@ fi
 done
 test -n "$MAKEINFO" || MAKEINFO="${MISSING} makeinfo"
 
+else
+  test -z "${MISSING}" && test -z "${SHELL}" && echo "skipping use of missing script for makeinfo when it might fail"
+  for ac_prog in makeinfo gmakeinfo
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+printf %s "checking for $ac_word... " >&6; }
+if test ${ac_cv_prog_MAKEINFO+y}
+then :
+  printf %s "(cached) " >&6
+else case e in #(
+  e) if test -n "$MAKEINFO"; then
+  ac_cv_prog_MAKEINFO="$MAKEINFO" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  case $as_dir in #(((
+    '') as_dir=./ ;;
+    */) ;;
+    *) as_dir=$as_dir/ ;;
+  esac
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir$ac_word$ac_exec_ext"; then
+    ac_cv_prog_MAKEINFO="$ac_prog"
+    printf "%s\n" "$as_me:${as_lineno-$LINENO}: found $as_dir$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi ;;
+esac
+fi
+MAKEINFO=$ac_cv_prog_MAKEINFO
+if test -n "$MAKEINFO"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $MAKEINFO" >&5
+printf "%s\n" "$MAKEINFO" >&6; }
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+
+
+  test -n "$MAKEINFO" && break
+done
+test -n "$MAKEINFO" || MAKEINFO="makeinfo"
+
+fi
 case " ${build_configdirs} " in
-  *" texinfo "*) MAKEINFO='$$r/$(BUILD_SUBDIR)/texinfo/makeinfo/makeinfo' ;;
+  *" texinfo "*)
+    echo "texinfo is in build_configdirs; will attempt to use the built makeinfo"
+    MAKEINFO='$$r/$(BUILD_SUBDIR)/texinfo/makeinfo/makeinfo' ;;
   *)
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking version of ${MAKEINFO}" >&5
+printf %s "checking version of ${MAKEINFO}... " >&6; }
+    MAKEINFO_VERSION=""
+    if test -n "${MAKEINFO}" && test -x "${MAKEINFO}"; then
+      export MAKEINFO_VERSION="`${MAKEINFO} --version`"
+    fi
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: ${MAKEINFO_VERSION}" >&5
+printf "%s\n" "${MAKEINFO_VERSION}" >&6; }
 
     # For an installed makeinfo, we require it to be from texinfo 4.7 or
     # higher, else we use the "missing" dummy.
-    if ${MAKEINFO} --version \
+    if test -n "${MAKEINFO}" && test -x "${MAKEINFO}" && ${MAKEINFO} --version \
        | egrep 'texinfo[^0-9]*(4\.([7-9]|[1-9][0-9])|[5-9]|[1-9][0-9])' >/dev/null 2>&1; then
-      :
+      echo "version of makeinfo is fine"
+    elif test "x${MISSING}" != "x"; then
+      test -n "${MISSING}" && echo "falling back to use ${MISSING} script" && export MAKEINFO="${MISSING} makeinfo"
     else
-      MAKEINFO="${MISSING} makeinfo"
+      test -z "${MISSING}" && echo "need to fall back to use the missing script, but the variable for it is unset!" >&2 && export MAKEINFO="false"
     fi
     ;;
 
