warnings and configury and stuff, now with clang-3.6 and gcc6
Change-Id: I9d824fe284cbd91f0bba09042f5b2f44287ead2f

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -803,6 +803,7 @@ target_subdir
 host_subdir
 build_subdir
 AWK
+AUTOCONF
 AM_BACKSLASH
 AM_DEFAULT_VERBOSITY
 AM_DEFAULT_V
@@ -822,6 +823,7 @@ INSTALL_SCRIPT
 INSTALL_PROGRAM
 AUTOOPTS_LIBS
 AUTOGEN_LDFLAGS
+AUTOGEN_BAD_LDFLAGS
 AUTOOPTS_CFLAGS
 AUTOGEN
 AUTOOPTS_CONFIG
@@ -1608,7 +1610,6 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-multilib       build many library versions (default off)
   --disable-opts-test     Do not try to run a test AutoOpts program
-
   --enable-silent-rules   less verbose build output (undo: "make V=1")
   --disable-silent-rules  verbose build output (undo: "make V=0")
   --enable-as-accelerator-for=ARG
@@ -1673,7 +1674,6 @@ Optional Packages:
   --with-opts-prefix=PFX  Prefix where autoopts is installed (optional)
   --with-opts-exec-prefix=PFX
                           Exec prefix where autoopts is installed (optional)
-
   --with-x                use the X Window System
   --with-mpc=PATH         specify prefix directory for installed MPC package.
                           Equivalent to --with-mpc-include=PATH/include plus
@@ -4530,33 +4530,30 @@ if test "${with_opts_prefix+set}" = set; then :
 fi
 
 
-
 # Check whether --with-opts-exec-prefix was given.
 if test "${with_opts_exec_prefix+set}" = set; then :
   withval=$with_opts_exec_prefix;
 fi
-
 
 # Check whether --enable-opts-test was given.
 if test "${enable_opts_test+set}" = set; then :
   enableval=$enable_opts_test;
 fi
 
-
-  if test x$with_opts_exec_prefix != x ; then
-    aocfg_args="$aocfg_args --exec-prefix=$with_opts_exec_prefix"
+  if test "x${with_opts_exec_prefix}" != "x"; then
+    aocfg_args="${aocfg_args} --exec-prefix=${with_opts_exec_prefix}"
     if test x${AUTOOPTS_CONFIG+set} != xset ; then
-      AUTOOPTS_CONFIG=$with_opts_exec_prefix/bin/autoopts-config
+      AUTOOPTS_CONFIG=${with_opts_exec_prefix}/bin/autoopts-config
     fi
   fi
-  if test x$with_opts_prefix != x ; then
-     aocfg_args="$aocfg_args --prefix=$with_opts_prefix"
+  if test "x${with_opts_prefix}" != "x"; then
+     aocfg_args="${aocfg_args} --prefix=${with_opts_prefix}"
     if test x${AUTOOPTS_CONFIG+set} != xset ; then
-      AUTOOPTS_CONFIG=$with_opts_prefix/bin/autoopts-config
+      AUTOOPTS_CONFIG=${with_opts_prefix}/bin/autoopts-config
     fi
   fi
-  if test -n "$AUTOOPTS_CONFIG"; then
-    :
+  if test -n "${AUTOOPTS_CONFIG}"; then
+    test -x "${AUTOOPTS_CONFIG}"
   else
     # Extract the first word of "autoopts-config", so it can be a program name with args.
 set dummy autoopts-config; ac_word=$2
@@ -4603,35 +4600,43 @@ fi
   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for compatible autoopts version" >&5
 $as_echo_n "checking for compatible autoopts version... " >&6; }
   no_autoopts=""
-  if test "$AUTOOPTS_CONFIG" = "no" ; then
+  if test "x${AUTOOPTS_CONFIG}" = "xno"; then
     no_autoopts=yes
   else
-    AUTOGEN=`$AUTOOPTS_CONFIG $aocfg_args --autogen`
-    AUTOOPTS_CFLAGS=`$AUTOOPTS_CONFIG $aocfg_args --cflags`
-    AUTOGEN_LDFLAGS=`$AUTOOPTS_CONFIG $aocfg_args --pkgdatadir`
-    AUTOOPTS_LIBS=`$AUTOOPTS_CONFIG $aocfg_args --libs`
-    aocfg_version=`$AUTOOPTS_CONFIG $aocfg_args --version`
+    AUTOGEN=`${AUTOOPTS_CONFIG} ${aocfg_args} --autogen`
+    AUTOOPTS_CFLAGS=`${AUTOOPTS_CONFIG} ${aocfg_args} --cflags`
+    ## Wait, is this correct?
+    AUTOGEN_LDFLAGS=`${AUTOOPTS_CONFIG} ${aocfg_args} --pkgdatadir`
+    ## Just in case it is incorrect, assign it to a different variable:
+    AUTOGEN_BAD_LDFLAGS="${AUTOGEN_LDFLAGS}"
+    ## ...and overwrite it with a more intuitively-correct value:
+    AUTOGEN_LDFLAGS=`${AUTOOPTS_CONFIG} ${aocfg_args} --ldflags`
+    AUTOOPTS_LIBS=`${AUTOOPTS_CONFIG} ${aocfg_args} --libs`
+    aocfg_version=`${AUTOOPTS_CONFIG} ${aocfg_args} --version`
     save_IFS=$IFS
     IFS=' :'
     set -- $aocfg_version
     IFS=$save_IFS
-    aocfg_current=5.17.4
-    aocfg_revision=
-    aocfg_age=
-    aocfg_currev=5.17.4.
-    if test "x$enable_opts_test" != "xno" ; then
+    ## I think these are supposed to be shell variables instead of m4-level
+    ## argument parameters, so add the extra brackets to make sure that
+    ## they are interpreted that way:
+    aocfg_current=${1}
+    aocfg_revision=${2}
+    aocfg_age=${3}
+    aocfg_currev=${1}.${2}
+    if test "x${enable_opts_test}" != "xno"; then
       ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-      ac_save_CFLAGS="$CFLAGS"
-      ac_save_LDFLAGS="$LDFLAGS"
-      ac_save_LIBS="$LIBS"
-      CFLAGS="$CFLAGS $AUTOOPTS_CFLAGS"
-      LDFLAGS="$LDFLAGS $AUTOOPTS $CFLAGS"
-      LIBS="$LIBS $AUTOOPTS_LIBS"
+      ac_save_CFLAGS="${CFLAGS}"
+      ac_save_LDFLAGS="${LDFLAGS}"
+      ac_save_LIBS="${LIBS}"
+      CFLAGS="${CFLAGS} ${AUTOOPTS_CFLAGS}"
+      LDFLAGS="${LDFLAGS} ${AUTOOPTS_CFLAGS}"
+      LIBS="${LIBS} ${AUTOOPTS_LIBS}"
 
       rm -f confopts.def conf.optstest
       if test "$cross_compiling" = yes; then :
@@ -4649,7 +4654,7 @@ else
 #endif /* !OPTIONS_VER_TO_NUM */
 
 static char const zBadVer[] = "\n\\
-*** 'autoopts-config --version' returned $aocfg_version,\n\\
+*** 'autoopts-config --version' returned ${aocfg_version},\n\\
 ***                but autoopts returned %d:%d:0\n\\
 ***             and the header file says %s\n\\
 *** These should all be consistent.\n\n\\
@@ -4688,7 +4693,7 @@ main (int argc, char ** argv)
     /*
      *  Test autoopts-config against header version
      */
-    if (   OPTIONS_VER_TO_NUM($aocfg_current, $aocfg_revision)
+    if (   OPTIONS_VER_TO_NUM(${aocfg_current}, ${aocfg_revision})
         != OPTIONS_STRUCT_VERSION) {
         printf("*** autoopts header file version "OPTIONS_VERSION_STRING"\n"
                "*** does not match autoopts-config value $aocfg_version\n"
@@ -4709,9 +4714,9 @@ rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
   conftest.$ac_objext conftest.beam conftest.$ac_ext
 fi
 
-      CFLAGS="$ac_save_CFLAGS"
-      LDFLAGS="$ac_save_LDFLAGS"
-      LIBS="$ac_save_LIBS"
+      CFLAGS="${ac_save_CFLAGS}"
+      LDFLAGS="${ac_save_LDFLAGS}"
+      LIBS="${ac_save_LIBS}"
       ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4721,14 +4726,14 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
     fi
   fi
 
-  if test "x$no_autoopts" = x ; then
+  if test "x${no_autoopts}" = "x"; then
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
     :
   else
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-    if test "$AUTOOPTS_CONFIG" = "no" ; then
+    if test "x${AUTOOPTS_CONFIG}" = "xno"; then
       cat <<- _EOF_
 	*** The autoopts-config script installed by AutoGen could not be found
 	*** If AutoGen was installed in PREFIX, make sure PREFIX/bin is in
@@ -4740,8 +4745,8 @@ $as_echo "no" >&6; }
          :
        else
          echo "*** Could not run autoopts test program, checking why..."
-         CFLAGS="$CFLAGS $AUTOOPTS_CFLAGS"
-         LIBS="$LIBS $AUTOOPTS_LIBS"
+         CFLAGS="${CFLAGS} ${AUTOOPTS_CFLAGS}"
+         LIBS="${LIBS} ${AUTOOPTS_LIBS}"
          ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4753,7 +4758,15 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 #include <autoopts/options.h>
 #include <stdio.h>
+#include <string.h>
 
+int
+main ()
+{
+return strcmp("$aocfg_current:$aocfg_revision:$aocfg_age", optionVersion());
+  ;
+  return 0;
+}
 _ACEOF
 if ac_fn_c_try_link "$LINENO"; then :
    cat << _EOF_
@@ -4780,8 +4793,8 @@ _EOF_
 fi
 rm -f core conftest.err conftest.$ac_objext \
     conftest$ac_exeext conftest.$ac_ext
-          CFLAGS="$ac_save_CFLAGS"
-          LIBS="$ac_save_LIBS"
+          CFLAGS="${ac_save_CFLAGS}"
+          LIBS="${ac_save_LIBS}"
           ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4795,14 +4808,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
      AUTOOPTS_LIBS=""
      :
   fi
-
-
-
-
+            ## clean up after ourselves:
   rm -f confopts.def conf.optstest
-
-# TODO: figure out how to pass the --disable-opts-test configure flag
-# to the configure script in the "utils" subdirectory.
 
 # Get 'install' or 'install-sh' and its variants:
 # Find a good install program.  We prefer a C program (faster),
@@ -5345,6 +5352,27 @@ AM_BACKSLASH='\'
 : ${AM_DEFAULT_VERBOSITY=1}
 : ${AM_V=${AM_DEFAULT_VERBOSITY}}
 : ${AM_DEFAULT_V=${AM_DEFAULT_VERBOSITY}}
+
+
+  if test x"${MISSING+set}" != xset; then
+  case $am_aux_dir in
+  *\ * | *\	*)
+    MISSING="\${SHELL} \"$am_aux_dir/missing\"" ;;
+  *)
+    MISSING="\${SHELL} $am_aux_dir/missing" ;;
+  esac
+fi
+# Use eval to expand $SHELL
+if eval "$MISSING --is-lightweight"; then
+  am_missing_run="$MISSING "
+else
+  am_missing_run=
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: 'missing' script is too old or missing" >&5
+$as_echo "$as_me: WARNING: 'missing' script is too old or missing" >&2;}
+fi
+
+
+AUTOCONF=${AUTOCONF-"${am_missing_run}autoconf"}
 
 # Set srcdir to "." if that is what it is.
 # This is important for multilib support.
@@ -14192,23 +14220,6 @@ fi
   test -n "$CONFIGURED_MAKEINFO" && break
 done
 test -n "$CONFIGURED_MAKEINFO" || CONFIGURED_MAKEINFO="${MISSING} makeinfo"
-
-if test x"${MISSING+set}" != xset; then
-  case $am_aux_dir in
-  *\ * | *\	*)
-    MISSING="\${SHELL} \"$am_aux_dir/missing\"" ;;
-  *)
-    MISSING="\${SHELL} $am_aux_dir/missing" ;;
-  esac
-fi
-# Use eval to expand $SHELL
-if eval "$MISSING --is-lightweight"; then
-  am_missing_run="$MISSING "
-else
-  am_missing_run=
-  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: 'missing' script is too old or missing" >&5
-$as_echo "$as_me: WARNING: 'missing' script is too old or missing" >&2;}
-fi
 
 for ac_prog in flex lex
 do
diff --git a/src/dejagnu/Makefile.in b/src/dejagnu/Makefile.in
--- a/src/dejagnu/Makefile.in
+++ b/src/dejagnu/Makefile.in
@@ -608,12 +608,12 @@ TLCSH = @TCLSH@
 # renamed because the old variable overrode the default Automake one:
 RUNTESTDEFAULTFLAGSLOCAL = --srcdir $(srcdir)/testsuite RUNTEST=$(RUNTESTLOCAL)
 RUNTESTLOCAL = ` \
-  if [ -f ${srcdir}/runtest$(EXEEXT) ] ; then \
+  if [ -f ${srcdir}/runtest$(EXEEXT) ]; then \
     echo ${srcdir}/runtest$(EXEEXT); \
-  else echo "ERROR: runtest not found" ; exit 1; fi`
+  else echo "ERROR: runtest not found"; exit 1; fi`
 
 AM_CXXFLAGS = -I$(top_srcdir) -ggdb -Wall
-AM_CFLAGS = -Wall -Wc++-compat -DHAVE_CONFIG_H
+AM_CFLAGS = -Wall -Wc++-compat -std=gnu89 -DHAVE_CONFIG_H
 OFILES = testglue.o stub-loader.o
 ALL_OFILES = $(OFILES) i960glue.o
 CLEANFILES = x.log x.sum site.bak setval.tmp $(ALL_OFILES) *~
@@ -1872,10 +1872,10 @@ check-DEJAGNU-local:
 	@echo "Do nothing here, because we do NOT want to run the tests twice"
 .PHONY: check-DEJAGNU-local
 
-testglue.o: testglue.c
+testglue.o: testglue.c config.h
 	$(CC) $(CFLAGS) $(AM_CFLAGS) -o testglue.o -c testglue.c
 
-stub-loader.o: stub-loader.c
+stub-loader.o: stub-loader.c config.h dejagnu.h
 	$(CC) $(CFLAGS) $(AM_CFLAGS) -o stub-loader.o -c stub-loader.c
 
 i960glue.o: i960glue.c
diff --git a/src/utils/configure b/src/utils/configure
--- a/src/utils/configure
+++ b/src/utils/configure
@@ -633,6 +633,7 @@ install_subdirs
 all_subdirs
 AUTOOPTS_LIBS
 AUTOGEN_LDFLAGS
+AUTOGEN_BAD_LDFLAGS
 AUTOOPTS_CFLAGS
 AUTOGEN
 AUTOOPTS_CONFIG
@@ -640,6 +641,7 @@ LIBOBJS
 EGREP
 GREP
 CPP
+AUTOCONF
 am__fastdepCCAS_FALSE
 am__fastdepCCAS_TRUE
 CCASDEPMODE
@@ -655,6 +657,9 @@ CCASFLAGS
 CCAS
 ac_ct_AR
 AR
+ac_ct_CXX
+CXXFLAGS
+CXX
 OBJEXT
 EXEEXT
 ac_ct_CC
@@ -731,6 +736,9 @@ CFLAGS
 LDFLAGS
 LIBS
 CPPFLAGS
+CXX
+CXXFLAGS
+CCC
 CCAS
 CCASFLAGS
 CPP'
@@ -1354,14 +1362,12 @@ Optional Features:
                           speeds up one-time build
   --disable-opts-test     Do not try to run a test AutoOpts program
 
-
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-opts-prefix=PFX  Prefix where autoopts is installed (optional)
   --with-opts-exec-prefix=PFX
                           Exec prefix where autoopts is installed (optional)
-
 
 Some influential environment variables:
   CC          C compiler command
@@ -1371,6 +1377,8 @@ Some influential environment variables:
   LIBS        libraries to pass to the linker, e.g. -l<library>
   CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
               you have headers in a nonstandard directory <include dir>
+  CXX         C++ compiler command
+  CXXFLAGS    C++ compiler flags
   CCAS        assembler compiler command (defaults to CC)
   CCASFLAGS   assembler compiler flags (defaults to CFLAGS)
   CPP         C preprocessor
@@ -1492,6 +1500,44 @@ fi
   as_fn_set_status $ac_retval
 
 } # ac_fn_c_try_compile
+
+# ac_fn_cxx_try_compile LINENO
+# ----------------------------
+# Try to compile conftest.$ac_ext, and return whether this succeeded.
+ac_fn_cxx_try_compile ()
+{
+  as_lineno=${as_lineno-"$1"} as_lineno_stack=as_lineno_stack=$as_lineno_stack
+  rm -f conftest.$ac_objext
+  if { { ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+$as_echo "$ac_try_echo"; } >&5
+  (eval "$ac_compile") 2>conftest.err
+  ac_status=$?
+  if test -s conftest.err; then
+    grep -v '^ *+' conftest.err >conftest.er1
+    cat conftest.er1 >&5
+    mv -f conftest.er1 conftest.err
+  fi
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then :
+  ac_retval=0
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_retval=1
+fi
+  eval $as_lineno_stack; ${as_lineno_stack:+:} unset as_lineno
+  as_fn_set_status $ac_retval
+
+} # ac_fn_cxx_try_compile
 
 # ac_fn_c_try_cpp LINENO
 # ----------------------
@@ -3249,6 +3295,263 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
+ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+if test -z "$CXX"; then
+  if test -n "$CCC"; then
+    CXX=$CCC
+  else
+    if test -n "$ac_tool_prefix"; then
+  for ac_prog in g++ c++ gpp aCC CC cxx cc++ cl.exe FCC KCC RCC xlC_r xlC
+  do
+    # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
+set dummy $ac_tool_prefix$ac_prog; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_CXX+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$CXX"; then
+  ac_cv_prog_CXX="$CXX" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_CXX="$ac_tool_prefix$ac_prog"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi
+fi
+CXX=$ac_cv_prog_CXX
+if test -n "$CXX"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $CXX" >&5
+$as_echo "$CXX" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+    test -n "$CXX" && break
+  done
+fi
+if test -z "$CXX"; then
+  ac_ct_CXX=$CXX
+  for ac_prog in g++ c++ gpp aCC CC cxx cc++ cl.exe FCC KCC RCC xlC_r xlC
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for $ac_word" >&5
+$as_echo_n "checking for $ac_word... " >&6; }
+if ${ac_cv_prog_ac_ct_CXX+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  if test -n "$ac_ct_CXX"; then
+  ac_cv_prog_ac_ct_CXX="$ac_ct_CXX" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+    for ac_exec_ext in '' $ac_executable_extensions; do
+  if as_fn_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_ac_ct_CXX="$ac_prog"
+    $as_echo "$as_me:${as_lineno-$LINENO}: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+  done
+IFS=$as_save_IFS
+
+fi
+fi
+ac_ct_CXX=$ac_cv_prog_ac_ct_CXX
+if test -n "$ac_ct_CXX"; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_ct_CXX" >&5
+$as_echo "$ac_ct_CXX" >&6; }
+else
+  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+
+  test -n "$ac_ct_CXX" && break
+done
+
+  if test "x$ac_ct_CXX" = x; then
+    CXX="g++"
+  else
+    case $cross_compiling:$ac_tool_warned in
+yes:)
+{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: using cross tools not prefixed with host triplet" >&5
+$as_echo "$as_me: WARNING: using cross tools not prefixed with host triplet" >&2;}
+ac_tool_warned=yes ;;
+esac
+    CXX=$ac_ct_CXX
+  fi
+fi
+
+  fi
+fi
+# Provide some information about the compiler.
+$as_echo "$as_me:${as_lineno-$LINENO}: checking for C++ compiler version" >&5
+set X $ac_compile
+ac_compiler=$2
+for ac_option in --version -v -V -qversion; do
+  { { ac_try="$ac_compiler $ac_option >&5"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:${as_lineno-$LINENO}: $ac_try_echo\""
+$as_echo "$ac_try_echo"; } >&5
+  (eval "$ac_compiler $ac_option >&5") 2>conftest.err
+  ac_status=$?
+  if test -s conftest.err; then
+    sed '10a\
+... rest of stderr output deleted ...
+         10q' conftest.err >conftest.er1
+    cat conftest.er1 >&5
+  fi
+  rm -f conftest.er1 conftest.err
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }
+done
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether we are using the GNU C++ compiler" >&5
+$as_echo_n "checking whether we are using the GNU C++ compiler... " >&6; }
+if ${ac_cv_cxx_compiler_gnu+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+#ifndef __GNUC__
+       choke me
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+  ac_compiler_gnu=yes
+else
+  ac_compiler_gnu=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+ac_cv_cxx_compiler_gnu=$ac_compiler_gnu
+
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_cxx_compiler_gnu" >&5
+$as_echo "$ac_cv_cxx_compiler_gnu" >&6; }
+if test $ac_compiler_gnu = yes; then
+  GXX=yes
+else
+  GXX=
+fi
+ac_test_CXXFLAGS=${CXXFLAGS+set}
+ac_save_CXXFLAGS=$CXXFLAGS
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether $CXX accepts -g" >&5
+$as_echo_n "checking whether $CXX accepts -g... " >&6; }
+if ${ac_cv_prog_cxx_g+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_save_cxx_werror_flag=$ac_cxx_werror_flag
+   ac_cxx_werror_flag=yes
+   ac_cv_prog_cxx_g=no
+   CXXFLAGS="-g"
+   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+  ac_cv_prog_cxx_g=yes
+else
+  CXXFLAGS=""
+      cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+
+else
+  ac_cxx_werror_flag=$ac_save_cxx_werror_flag
+	 CXXFLAGS="-g"
+	 cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"; then :
+  ac_cv_prog_cxx_g=yes
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+   ac_cxx_werror_flag=$ac_save_cxx_werror_flag
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_prog_cxx_g" >&5
+$as_echo "$ac_cv_prog_cxx_g" >&6; }
+if test "$ac_test_CXXFLAGS" = set; then
+  CXXFLAGS=$ac_save_CXXFLAGS
+elif test $ac_cv_prog_cxx_g = yes; then
+  if test "$GXX" = yes; then
+    CXXFLAGS="-g -O2"
+  else
+    CXXFLAGS="-g"
+  fi
+else
+  if test "$GXX" = yes; then
+    CXXFLAGS="-O2"
+  else
+    CXXFLAGS=
+  fi
+fi
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
 
   # Expand $ac_aux_dir to an absolute path.
 am_aux_dir=`cd "$ac_aux_dir" && pwd`
@@ -3631,6 +3934,26 @@ else
 fi
 
 
+
+  if test x"${MISSING+set}" != xset; then
+  case $am_aux_dir in
+  *\ * | *\	*)
+    MISSING="\${SHELL} \"$am_aux_dir/missing\"" ;;
+  *)
+    MISSING="\${SHELL} $am_aux_dir/missing" ;;
+  esac
+fi
+# Use eval to expand $SHELL
+if eval "$MISSING --is-lightweight"; then
+  am_missing_run="$MISSING "
+else
+  am_missing_run=
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: 'missing' script is too old or missing" >&5
+$as_echo "$as_me: WARNING: 'missing' script is too old or missing" >&2;}
+fi
+
+
+AUTOCONF=${AUTOCONF-"${am_missing_run}autoconf"}
 
 # Checks for header files.
 ac_ext=c
@@ -4178,33 +4501,30 @@ if test "${with_opts_prefix+set}" = set; then :
 fi
 
 
-
 # Check whether --with-opts-exec-prefix was given.
 if test "${with_opts_exec_prefix+set}" = set; then :
   withval=$with_opts_exec_prefix;
 fi
-
 
 # Check whether --enable-opts-test was given.
 if test "${enable_opts_test+set}" = set; then :
   enableval=$enable_opts_test;
 fi
 
-
-  if test x$with_opts_exec_prefix != x ; then
-    aocfg_args="$aocfg_args --exec-prefix=$with_opts_exec_prefix"
+  if test "x${with_opts_exec_prefix}" != "x"; then
+    aocfg_args="${aocfg_args} --exec-prefix=${with_opts_exec_prefix}"
     if test x${AUTOOPTS_CONFIG+set} != xset ; then
-      AUTOOPTS_CONFIG=$with_opts_exec_prefix/bin/autoopts-config
+      AUTOOPTS_CONFIG=${with_opts_exec_prefix}/bin/autoopts-config
     fi
   fi
-  if test x$with_opts_prefix != x ; then
-     aocfg_args="$aocfg_args --prefix=$with_opts_prefix"
+  if test "x${with_opts_prefix}" != "x"; then
+     aocfg_args="${aocfg_args} --prefix=${with_opts_prefix}"
     if test x${AUTOOPTS_CONFIG+set} != xset ; then
-      AUTOOPTS_CONFIG=$with_opts_prefix/bin/autoopts-config
+      AUTOOPTS_CONFIG=${with_opts_prefix}/bin/autoopts-config
     fi
   fi
-  if test -n "$AUTOOPTS_CONFIG"; then
-    :
+  if test -n "${AUTOOPTS_CONFIG}"; then
+    test -x "${AUTOOPTS_CONFIG}"
   else
     # Extract the first word of "autoopts-config", so it can be a program name with args.
 set dummy autoopts-config; ac_word=$2
@@ -4251,35 +4571,43 @@ fi
   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for compatible autoopts version" >&5
 $as_echo_n "checking for compatible autoopts version... " >&6; }
   no_autoopts=""
-  if test "$AUTOOPTS_CONFIG" = "no" ; then
+  if test "x${AUTOOPTS_CONFIG}" = "xno"; then
     no_autoopts=yes
   else
-    AUTOGEN=`$AUTOOPTS_CONFIG $aocfg_args --autogen`
-    AUTOOPTS_CFLAGS=`$AUTOOPTS_CONFIG $aocfg_args --cflags`
-    AUTOGEN_LDFLAGS=`$AUTOOPTS_CONFIG $aocfg_args --pkgdatadir`
-    AUTOOPTS_LIBS=`$AUTOOPTS_CONFIG $aocfg_args --libs`
-    aocfg_version=`$AUTOOPTS_CONFIG $aocfg_args --version`
+    AUTOGEN=`${AUTOOPTS_CONFIG} ${aocfg_args} --autogen`
+    AUTOOPTS_CFLAGS=`${AUTOOPTS_CONFIG} ${aocfg_args} --cflags`
+    ## Wait, is this correct?
+    AUTOGEN_LDFLAGS=`${AUTOOPTS_CONFIG} ${aocfg_args} --pkgdatadir`
+    ## Just in case it is incorrect, assign it to a different variable:
+    AUTOGEN_BAD_LDFLAGS="${AUTOGEN_LDFLAGS}"
+    ## ...and overwrite it with a more intuitively-correct value:
+    AUTOGEN_LDFLAGS=`${AUTOOPTS_CONFIG} ${aocfg_args} --ldflags`
+    AUTOOPTS_LIBS=`${AUTOOPTS_CONFIG} ${aocfg_args} --libs`
+    aocfg_version=`${AUTOOPTS_CONFIG} ${aocfg_args} --version`
     save_IFS=$IFS
     IFS=' :'
     set -- $aocfg_version
     IFS=$save_IFS
-    aocfg_current=5.17.4
-    aocfg_revision=
-    aocfg_age=
-    aocfg_currev=5.17.4.
-    if test "x$enable_opts_test" != "xno" ; then
+    ## I think these are supposed to be shell variables instead of m4-level
+    ## argument parameters, so add the extra brackets to make sure that
+    ## they are interpreted that way:
+    aocfg_current=${1}
+    aocfg_revision=${2}
+    aocfg_age=${3}
+    aocfg_currev=${1}.${2}
+    if test "x${enable_opts_test}" != "xno"; then
       ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-      ac_save_CFLAGS="$CFLAGS"
-      ac_save_LDFLAGS="$LDFLAGS"
-      ac_save_LIBS="$LIBS"
-      CFLAGS="$CFLAGS $AUTOOPTS_CFLAGS"
-      LDFLAGS="$LDFLAGS $AUTOOPTS $CFLAGS"
-      LIBS="$LIBS $AUTOOPTS_LIBS"
+      ac_save_CFLAGS="${CFLAGS}"
+      ac_save_LDFLAGS="${LDFLAGS}"
+      ac_save_LIBS="${LIBS}"
+      CFLAGS="${CFLAGS} ${AUTOOPTS_CFLAGS}"
+      LDFLAGS="${LDFLAGS} ${AUTOOPTS_CFLAGS}"
+      LIBS="${LIBS} ${AUTOOPTS_LIBS}"
 
       rm -f confopts.def conf.optstest
       if test "$cross_compiling" = yes; then :
@@ -4297,7 +4625,7 @@ else
 #endif /* !OPTIONS_VER_TO_NUM */
 
 static char const zBadVer[] = "\n\\
-*** 'autoopts-config --version' returned $aocfg_version,\n\\
+*** 'autoopts-config --version' returned ${aocfg_version},\n\\
 ***                but autoopts returned %d:%d:0\n\\
 ***             and the header file says %s\n\\
 *** These should all be consistent.\n\n\\
@@ -4336,7 +4664,7 @@ main (int argc, char ** argv)
     /*
      *  Test autoopts-config against header version
      */
-    if (   OPTIONS_VER_TO_NUM($aocfg_current, $aocfg_revision)
+    if (   OPTIONS_VER_TO_NUM(${aocfg_current}, ${aocfg_revision})
         != OPTIONS_STRUCT_VERSION) {
         printf("*** autoopts header file version "OPTIONS_VERSION_STRING"\n"
                "*** does not match autoopts-config value $aocfg_version\n"
@@ -4357,9 +4685,9 @@ rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
   conftest.$ac_objext conftest.beam conftest.$ac_ext
 fi
 
-      CFLAGS="$ac_save_CFLAGS"
-      LDFLAGS="$ac_save_LDFLAGS"
-      LIBS="$ac_save_LIBS"
+      CFLAGS="${ac_save_CFLAGS}"
+      LDFLAGS="${ac_save_LDFLAGS}"
+      LIBS="${ac_save_LIBS}"
       ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4369,14 +4697,14 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
     fi
   fi
 
-  if test "x$no_autoopts" = x ; then
+  if test "x${no_autoopts}" = "x"; then
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
     :
   else
     { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
-    if test "$AUTOOPTS_CONFIG" = "no" ; then
+    if test "x${AUTOOPTS_CONFIG}" = "xno"; then
       cat <<- _EOF_
 	*** The autoopts-config script installed by AutoGen could not be found
 	*** If AutoGen was installed in PREFIX, make sure PREFIX/bin is in
@@ -4388,8 +4716,8 @@ $as_echo "no" >&6; }
          :
        else
          echo "*** Could not run autoopts test program, checking why..."
-         CFLAGS="$CFLAGS $AUTOOPTS_CFLAGS"
-         LIBS="$LIBS $AUTOOPTS_LIBS"
+         CFLAGS="${CFLAGS} ${AUTOOPTS_CFLAGS}"
+         LIBS="${LIBS} ${AUTOOPTS_LIBS}"
          ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4401,7 +4729,15 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 #include <autoopts/options.h>
 #include <stdio.h>
+#include <string.h>
 
+int
+main ()
+{
+return strcmp("$aocfg_current:$aocfg_revision:$aocfg_age", optionVersion());
+  ;
+  return 0;
+}
 _ACEOF
 if ac_fn_c_try_link "$LINENO"; then :
    cat << _EOF_
@@ -4428,8 +4764,8 @@ _EOF_
 fi
 rm -f core conftest.err conftest.$ac_objext \
     conftest$ac_exeext conftest.$ac_ext
-          CFLAGS="$ac_save_CFLAGS"
-          LIBS="$ac_save_LIBS"
+          CFLAGS="${ac_save_CFLAGS}"
+          LIBS="${ac_save_LIBS}"
           ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4443,10 +4779,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
      AUTOOPTS_LIBS=""
      :
   fi
-
-
-
-
+            ## clean up after ourselves:
   rm -f confopts.def conf.optstest
 
 # Choose which subdirs to use:
