Update apple-gdb-1824-macos.yml
additional output

Change-Id: Ic6e233d44dcf9bd20bf9b467bf34e7895b7dc112

diff --git a/.github/workflows/apple-gdb-1824-macos.yml b/.github/workflows/apple-gdb-1824-macos.yml
--- a/.github/workflows/apple-gdb-1824-macos.yml
+++ b/.github/workflows/apple-gdb-1824-macos.yml
@@ -109,6 +109,7 @@ jobs:
         ./bootstrap || stat ./bootstrap || test -x ./bootstrap
         if test libltdl/configure -ot libltdl/configure.ac; then \
           if test -x libltdl/configure && test -s libltdl/configure; then \
+            echo "touch libltdl/configure"; \
             touch libltdl/configure; \
           elif test -x libltdl/configure~ && test -s libltdl/configure~; then \
             cp -vf libltdl/configure~ libltdl/configure; \
@@ -119,20 +120,30 @@ jobs:
           fi; \
         fi
         if test libltdl/Makefile.in -ot libltdl/Makefile.am; then \
+          echo "test -s libltdl/Makefile.in && touch libltdl/Makefile.in"; \
           test -s libltdl/Makefile.in && touch libltdl/Makefile.in; \
         fi
         if test libltdl/Makefile -ot libltdl/Makefile.in; then \
+          echo "test -s libltdl/Makefile && touch libltdl/Makefile"; \
           test -s libltdl/Makefile && touch libltdl/Makefile; \
         fi
         for subdir in libltdl libltdl/loaders libtool_gnu/libltdl/loaders loaders; do \
           if test -d "${subdir}" && test -w "${subdir}" && test ! -d "${subdir}"/.deps; then \
             mkdir -pv "${subdir}"/.deps; \
+            if test -w "${subdir}"/.deps && test ! -e "${subdir}"/.deps/.dirstamp; then \
+              echo "touch ${subdir}/.deps/.dirstamp"; \
+              touch "${subdir}"/.deps/.dirstamp; \
+            fi; \
           elif test -e "${subdir}"/.deps; then \
             stat "${subdir}"/.deps; \
+            if test -w "${subdir}"/.deps && test ! -e "${subdir}"/.deps/.dirstamp; then \
+              echo "touch ${subdir}/.deps/.dirstamp"; \
+              touch "${subdir}"/.deps/.dirstamp; \
+            fi; \
           elif test -r "${subdir}"; then \
-            find "${subdir}" -name '*.Plo' -print; \
+            (find "${subdir}" -name '*.Plo' -print) || echo "depfiles may be missing for ${subdir}"; \
           elif test -x "$(which sync)"; then \
-            sync && pwd; \
+            sync && echo "checking ${subdir} from $(pwd)"; \
           else \
             echo "unhandled possibility for ${subdir}"; \
           fi; \
@@ -146,15 +157,19 @@ jobs:
           fi; \
           if test -r "${subdir}"/.deps; then \
             (find "${subdir}" -name '*.Tpo' -print) || echo "depfile generation may have failed for ${subdir}"; \
-          else \
+          elif test -d "${subdir}" && test ! -d "${subdir}"/.deps; then \
             echo "depdir generation may have failed for ${subdir}"; \
+          elif test ! -d "${subdir}"; then \
+            echo "${subdir} is not an extant subdirectory"; \
+          else \
+            echo "something about ${subdir} may require fixing"; \
           fi; \
         done
         sync && echo "hopefully libtool_gnu timestamps will be fine..."
     - name: Full build to get anything that might have been missed
       run: |
         cd src
-        touch config.log
+        touch config.log || ls ./*.log
         if test -x "$(which nproc)" && test "$(nproc)" -ge 2; then \
           echo "nproc says we can use $(nproc) build jobs"; \
           if test "$(nproc)" -eq 4; then \
