more warnings & static analysis of bfd
Change-Id: I6c5f1e903bc9bfce84450d35bcd3ee0d271cf954

diff --git a/.github/workflows/apple-gdb-1824-macos.yml b/.github/workflows/apple-gdb-1824-macos.yml
--- a/.github/workflows/apple-gdb-1824-macos.yml
+++ b/.github/workflows/apple-gdb-1824-macos.yml
@@ -84,8 +84,16 @@ jobs:
     - run: cd src && make check-libiberty
     - run: cd src && make -C tcl/unix tcltest
     - run: cd src && for dir in sim expect dejagnu itcl libgui; do if test -r ${dir}/Makefile; then make check-${dir} V=0 RUNTESTFLAGS="-v"; elif test -d ${dir}; then ls ${dir}/Makefile*; else echo "skipping testing ${dir}"; fi; done
-    - run: cd src && make check-bfd
-      if: matrix.compiler == 'clang'
+    - run: |
+        cd src
+        if test ${{ matrix.compiler }} == clang; then \
+          make check-bfd; \
+        elif test ${{ matrix.compiler }} == gcc; then \
+          cd bfd; \
+          make check-DEJAGNU; \
+        else \
+          echo "error, unhandled compiler!" >&2 && exit 1; \
+        fi
     - run: cd src && make check-opcodes
     # (dejagnu is now moved into the loop above)
     - run: cd src && make check-intl
