Update codeql.yml
a bit more tinkering

Change-Id: I87386fad32c99d3c0049ef68f427ce0ec3fc9687

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -163,13 +163,28 @@ jobs:
       if: matrix.language == 'c-cpp' && success()
       run: |
         cd src
+        if test -d autogen; then \
+          pushd autogen; \
+          if test -x ./configure; then \
+            ./configure --disable-werror --enable-silent-rules --disable-option-checking CFLAGS="-w" || stat -t ./configure; \
+          elif test -x ./config.status; then \
+            ./config.status || stat -t ./config.status; \
+          elif test -f Makefile; then \
+            make V=0 || stat -t Makefile; \
+          else \
+            pwd && ls; \
+          fi; \
+          popd; \
+        else \
+          echo "warning: autogen appears to be missing?"; \
+        fi
         # shellcheck disable=SC2001,SC2235
         for subdir in autogen/agen5 autogen/autoopts autogen/columns autogen/compat autogen/getdefs autogen/snprintfv autogen/xml2ag bfd bfd/doc binutils dejagnu dejagnu/contrib/bluegnu2.0.3/example/calc dejagnu/example/calc electric-fence expect expect/example expect/testsuite gdb gdb/gdbserver gdb/gnulib gdb/gnulib/import gdb/multi-ice gdb/nlm gdb/rdi-share gdb/rem-multi_old gdb/testsuite gdb/testsuite/gdb.apple gdb/testsuite/gdb.apple/debug-in-ofile gdb/testsuite/gdb.apple/gused gdb/testsuite/gdb.apple/xcode gdb/testsuite/gdb.arch gdb/testsuite/gdb.base gdb/testsuite/gdb.btrace gdb/testsuite/gdb.cell gdb/testsuite/gdb.dwarf2 gdb/testsuite/gdb.gdbtk gdb/testsuite/gdb.guile gdb/testsuite/gdb.hp gdb/testsuite/gdb.hp/gdb.aCC gdb/testsuite/gdb.hp/gdb.base-hp gdb/testsuite/gdb.hp/gdb.compat gdb/testsuite/gdb.hp/gdb.defects gdb/testsuite/gdb.linespec gdb/testsuite/gdb.mi gdb/testsuite/gdb.modula2 gdb/testsuite/gdb.multi gdb/testsuite/gdb.opt gdb/testsuite/gdb.perf gdb/testsuite/gdb.python gdb/testsuite/gdb.reverse gdb/testsuite/gdb.server gdb/testsuite/gdb.stabs gdb/testsuite/gdb.threads gdb/testsuite/gdb.trace gdb/tui intl itcl/itcl/win itcl/itk/win libbacktrace libdecnumber libgui/src libiberty libiberty/testsuite libtool_gnu/libltdl libtool_gnu/tests/cdemo libtool_gnu/tests/demo libtool_gnu/tests/depdemo libtool_gnu/tests/depdemo/l1 libtool_gnu/tests/depdemo/l2 libtool_gnu/tests/depdemo/l3 libtool_gnu/tests/depdemo/l4 libtool_gnu/tests/f77demo libtool_gnu/tests/fcdemo libtool_gnu/tests/mdemo libtool_gnu/tests/mdemo2 libtool_gnu/tests/pdemo mmalloc opcodes readline readline/examples readline/examples/rlfe.dir sim/common sim/igen sim/testsuite/common tcl/unix tcl/unix/dltest tcl/win tk/unix tk/win utils/amd-udi/mondfe utils/amd-udi/montip utils/amd-udi/udi utils/decomment.tproj utils/misc/doschk utils/relpath.tproj utils/sparclite utils/spu utils/wince zlib zlib/contrib/minizip; do \
           if test -e "${subdir}/Makefile" || test -x "${subdir}/configure"; then \
             pushd "${subdir}"; \
             if test ! -r Makefile && test -x ./configure; then \
               echo "configuring in ${subdir}"; \
-              ./configure --disable-werror --enable-silent-rules --disable-option-checking || stat -t ./configure; \
+              ./configure --disable-werror --enable-silent-rules --disable-option-checking CFLAGS="-w" || stat -t ./configure; \
             elif test ! -e Makefile && test -x ./config.status; then \
               echo "checking with ./config.status in ${subdir}"; \
               ./config.status || stat -t ./config.status; \
@@ -194,7 +209,7 @@ jobs:
           cobjfile="$(echo "${cfile}" | sed "s/\.c/.o/g")"; \
           if test ! -e "${cobjfile}"; then \
             echo "One last attempt at compiling ${cfile}..."; \
-            gcc -c "${cfile}" || gcc -c -I. "${cfile}" || gcc -c -I. -I.. "${cfile}" || stat -t "${cfile}" || echo "cfile is ${cfile}"; \
+            gcc -c -w "${cfile}" || gcc -c -w -I. "${cfile}" || gcc -c -w -I. -I.. "${cfile}" || stat -t "${cfile}" || echo "cfile is ${cfile}"; \
           else \
             echo "object file ${cobjfile} already exists for ${cfile}."; \
             cp -v "${cobjfile}" "$(dirname "${cfile}")" || cp -v "${cobjfile}" . || cp -v "${cobjfile}" ..; \
@@ -224,7 +239,11 @@ jobs:
         for subdir in dejagnu/testsuite/libdejagnu gdb/testsuite/gdb.apple gdb/testsuite/gdb.apple/gused gdb/testsuite/gdb.apple/ld-r gdb/testsuite/gdb.btrace gdb/testsuite/gdb.c++ gdb/testsuite/gdb.cp gdb/testsuite/gdb.gdbtk gdb/testsuite/gdb.hp  gdb/testsuite/gdb.linespec gdb/testsuite/gdb.mi gdb/testsuite/gdb.python gdb/testsuite/gdb.trace; do \
           if test -e "${subdir}/Makefile" && test -r "${subdir}/Makefile"; then \
             pushd "${subdir}"; \
+            if test -w . && test -w Makefile && test -n "$(wc -l Makefile)"; then \
+              touch Makefile; \
+            fi; \
             for srcfile in *.cc; do \
+              echo "attempting to use $(which make) to compile ${srcfile} in ${subdir}"; \
               make "$(echo "${srcfile}" | sed "s/\.cc/.o/g")" || stat "${srcfile}"; \
             done; \
             cp -v ./*.o .. || ls ./*.o || pwd; \
@@ -243,7 +262,7 @@ jobs:
           pushd gdb/testsuite/gdb.apple; \
           make file-statics-cpp.o || stat file-statics-cpp.cpp; \
           make var-path-expr.o || stat var-path-expr.cpp; \
-          cp -v ./*.o .. || ls ./*.o; \
+          cp -v ./*.o .. || ls ./*.o || pwd; \
           popd; \
         fi
         # shellcheck disable=SC2044
@@ -253,7 +272,7 @@ jobs:
         if test -e gdb/testsuite/gdb.base/Makefile && test -e gdb/testsuite/gdb.base/langs2.cxx; then \
           pushd gdb/testsuite/gdb.base; \
           make langs2.o || stat langs2.cxx; \
-          cp -v ./*.o .. || ls ./*.o;
+          cp -v ./*.o .. || ls ./*.o || pwd; \
           popd; \
         fi
         # shellcheck disable=SC2044
@@ -263,7 +282,7 @@ jobs:
         if test -e mmalloc/Makefile; then \
           pushd mmalloc; \
           make mmallocplusplus.o || stat mmallocplusplus.cp; \
-          cp -v ./*.o .. || ls ./*.o; \
+          cp -v ./*.o .. || ls ./*.o || pwd; \
           popd; \
         fi
 
