messing with workflows some more
Change-Id: Ib7f801f190d574afa290e8c68831d9bcd9b68c1b

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -234,10 +234,15 @@ jobs:
           sync && echo "leaving $(pwd)..."; \
           popd || exit; \
         elif test ${{ matrix.language }} == 'javascript-typescript' && test -x "$(which node)"; then \
-          (find . -name '*.js' -print0 | xargs -0 node -c) || find . -name '*.js' -print -exec node -c '{}' ';'; \
+          (find . -name '*.js' -print0 | xargs -0 node -c) || \
+            find . -name '*.js' -print -exec node -c '{}' ';'; \
           if test -x "$(which npx)"; then \
             pushd src/texinfo/js || exit; \
-            (npx eslint -c build-aux/eslint.json info.js -f unix) || (npx tsc --allowJs --checkJS --noEmit --lib dom,es2017 info.js) || (npx uglifyjs info.js -o info.min.js --mangle --compress) || (npx modernizr -c build-aux/modernizr.json) || (npx esparse info.js info.js.json) || (npx esvalidate info.js); \
+            (npx eslint -c build-aux/eslint.json info.js -f unix) || \
+              (npx tsc --allowJs --checkJS --noEmit --lib dom,es2017 info.js) || \
+              (npx uglifyjs info.js -o info.min.js --mangle --compress) || \
+              (npx modernizr -c build-aux/modernizr.json) || \
+              (npx esparse info.js info.js.json) || (npx esvalidate info.js); \
             if test -e info.js && test ! -e info.js.json; then \
               (npx esparse info.js info.js.json) || (npx esvalidate info.js) \
                 || (if test -x "$(which jsc)"; then jsc info.js; \
@@ -302,7 +307,8 @@ jobs:
           stat "$(which csc)" || stat "$(which mcs)" || which -a dotnet; \
           sync && echo "TODO: find a proper linter for csharp…" && sleep 1; \
         else \
-          echo "unhandled case for syntax check step (matrix.language is ${{ matrix.language }})"; \
+          sync && echo "unhandled case for syntax check step!"; \
+          sync && echo "(matrix.language is ${{ matrix.language }})"; \
           sync && sleep 1; \
         fi
 
@@ -358,11 +364,17 @@ jobs:
         else \
           ./configure --enable-silent-rules; \
         fi
-        make -ki -C libcheckpoint || make -ki -C libcheckpoint -f Makefile_orig || make -ki -C macsbug || make -ki -C macsbug/gdb_plugin_support || (if test -x "$(which ant)"; then ant; fi)
+        make -ki -C libcheckpoint || \
+          make -ki -C libcheckpoint -f Makefile_orig || \
+          make -ki -C macsbug || make -ki -C macsbug/gdb_plugin_support || \
+          (if test -x "$(which ant)"; then ant; fi)
         cd src
         if test -x "$(which sccache)"; then \
-          ./configure --disable-werror --enable-silent-rules --disable-cgen-maint CC="sccache gcc" CXX="sccache g++" OBJC="sccache gcc" OBJCXX="sccache g++"; \
-          make configure-bfd V=0 CC="sccache gcc" CXX="sccache g++" OBJC="sccache gcc" OBJCXX="sccache g++"; \
+          ./configure --disable-werror --enable-silent-rules \
+            --disable-cgen-maint CC="sccache gcc" CXX="sccache g++" \
+            OBJC="sccache gcc" OBJCXX="sccache g++"; \
+          make configure-bfd V=0 CC="sccache gcc" CXX="sccache g++" \
+            OBJC="sccache gcc" OBJCXX="sccache g++"; \
           sync && stat -t bfd && sync; \
         else \
           ./configure --disable-werror --enable-silent-rules --disable-cgen-maint; \
@@ -378,21 +390,36 @@ jobs:
           sync && echo "skipping autogen"; \
         fi
         sync && make -C bfd diststuff V=0 && sync
-        echo "make all-bfd" && (time make -j"$(nproc)" all-bfd V=0) && echo "done making all-bfd"
-        echo "make all-opcodes" && (time make -j"$(nproc)" all-opcodes V=0) && echo "done making all-opcodes"
-        echo "make configure-binutils" && (time make configure-binutils V=0) && echo "done making configure-binutils"
-        echo "make all-binutils" && (time make all-binutils V=0) && echo "done making all-binutils"
-        echo "make all-cgen" && (time make all-cgen) && echo "done making all-cgen"
-        echo "make all-libiberty" && (time make -j"$(nproc)" all-libiberty) && echo "done making all-libiberty"
-        echo "make all-intl" && (time make all-intl) && echo "done making all-intl"
-        echo "make all-etc" && (time make all-etc) && echo "done making all-etc"
-        echo "make all-libdecnumber" && (time make all-libdecnumber) && echo "done making all-libdecnumber"
-        echo "make all-mmalloc" && (time make all-mmalloc) && echo "done making all-mmalloc"
+        echo "make all-bfd" && (time make -j"$(nproc)" all-bfd V=0) && \
+          echo "done making all-bfd"
+        echo "make all-opcodes" && (time make -j"$(nproc)" all-opcodes V=0) && \
+          echo "done making all-opcodes"
+        echo "make configure-binutils" && (time make configure-binutils V=0) && \
+          echo "done making configure-binutils"
+        echo "make all-binutils" && (time make all-binutils V=0) && \
+          echo "done making all-binutils"
+        echo "make all-cgen" && (time make all-cgen) && \
+          echo "done making all-cgen"
+        echo "make all-libiberty" && (time make -j"$(nproc)" all-libiberty) && \
+          echo "done making all-libiberty"
+        echo "make all-intl" && (time make all-intl) && \
+          echo "done making all-intl"
+        echo "make all-etc" && (time make all-etc) && \
+          echo "done making all-etc"
+        echo "make all-libdecnumber" && (time make all-libdecnumber) && \
+          echo "done making all-libdecnumber"
+        echo "make all-mmalloc" && (time make all-mmalloc) && \
+          echo "done making all-mmalloc"
         make configure-electric-fence
         make configure-readline
         for dir in libtool_gnu sim utils tcl expect dejagnu itcl tk libgui; do \
           if test -e ${dir}/configure; then \
-            make configure-${dir} || (if test -e ${dir}/config.cache; then cat ${dir}/config.cache >&2 && exit 1; fi); \
+            make configure-${dir} || \
+              (if test -e ${dir}/config.cache; then \
+                 cat ${dir}/config.cache >&2 && exit 1; \
+               elif test -r ${dir}/config.status; then \
+                 stat ${dir}/config.status && wc -l ${dir}/config.status; \
+               else ls ${dir}; fi); \
           elif test -d ${dir}; then \
             ls ${dir}/configure*; \
           else \
@@ -401,28 +428,39 @@ jobs:
         done
         for dir in sim utils tcl expect dejagnu itcl tk libgui; do \
           if test -e ${dir}/Makefile; then \
-            echo "doing make in ${dir}" && (time make -j"$(nproc)" -C ${dir}) && echo "done running make in ${dir}"; \
+            echo "doing make in ${dir}" && \
+              (time make -j"$(nproc)" -C ${dir}) && \
+              echo "done running make in ${dir}"; \
           elif test -d ${dir}; then \
             ls ${dir}/Makefile*; \
           else \
             sync && echo "skipping ${dir}"; \
           fi; \
         done
-        echo "make configure-gdb" && (time make configure-gdb) && echo "done making configure-gdb"
-        echo "make all-gdb" && (time make all-gdb) && echo "done making all-gdb"
-        echo "make check-libiberty" && make check-libiberty && echo "done making check-libiberty"
+        echo "make configure-gdb" && (time make configure-gdb) && \
+          echo "done making configure-gdb"
+        echo "make all-gdb" && (time make all-gdb) && \
+          echo "done making all-gdb"
+        echo "make check-libiberty" && make check-libiberty && \
+          echo "done making check-libiberty"
         for dir in cgen sim expect dejagnu itcl libgui; do \
           if test -e ${dir}/Makefile; then \
-            echo "make check-${dir}" && (time make check-${dir} V=0 RUNTESTFLAGS="-v") && echo "done making check-${dir}"; \
+            echo "make check-${dir}" && \
+              (time make check-${dir} V=0 RUNTESTFLAGS="-v") && \
+              echo "done making check-${dir}"; \
           elif test -d ${dir}; \
             then ls ${dir}/Makefile*; \
           else \
             sync && echo "skipping testing ${dir}"; \
           fi; \
         done
-        echo "make check-opcodes" && (time make -j"$(nproc)" check-opcodes V=0) && echo "done making check-opcodes"
-        echo "make check-intl" && (time make check-intl) && echo "done making check-intl"
-        echo "make check-utils" && (time make check-utils) && echo "done making check-utils"
+        echo "make check-opcodes" && \
+          (time make -j"$(nproc)" check-opcodes V=0) && \
+          echo "done making check-opcodes"
+        echo "make check-intl" && (time make check-intl) && \
+          echo "done making check-intl"
+        echo "make check-utils" && (time make check-utils) && \
+          echo "done making check-utils"
 
     - name: Debug failure
       if: "${{ failure() }}"
@@ -447,7 +485,8 @@ jobs:
             export CXX="sccache g++"; \
           fi; \
         fi
-        make -ki -C libcheckpoint -f Makefile_orig RC_CFLAGS="-std=gnu89 -w -Wno-error" || stat -t libcheckpoint
+        make -ki -C libcheckpoint -f Makefile_orig \
+          RC_CFLAGS="-std=gnu89 -w -Wno-error" || stat -t libcheckpoint
         make -ki -C macsbug || make -ki -C macsbug/gdb_plugin_support || \
           stat -t macsbug
         cd src
@@ -483,9 +522,12 @@ jobs:
           pushd autogen; \
           if test -x "$(which guile18-build)" && test -e ./configure; then \
             sync && echo "running autogen configure script under $(which guile18-build)…"; \
-            guile18-build ./configure --disable-werror --enable-silent-rules --disable-option-checking CFLAGS="-w" || stat -t ./configure; \
+            guile18-build ./configure --disable-werror --enable-silent-rules \
+              --disable-option-checking CFLAGS="-w" || stat -t ./configure; \
           elif test -x ./configure && test -r ./configure && test -w .; then \
-            ./configure --disable-werror --enable-silent-rules --disable-option-checking --disable-dependency-tracking CFLAGS="-w" || stat -t ./configure; \
+            ./configure --disable-werror --enable-silent-rules \
+              --disable-option-checking --disable-dependency-tracking \
+              CFLAGS="-w" || stat -t ./configure; \
           elif test -x ./config.status && test -r ./config.status && test -w .; then \
             ./config.status || stat -t ./config.status; \
           elif test -f Makefile && test -r Makefile && test -w .; then \
@@ -503,7 +545,8 @@ jobs:
             pushd "${subdir}"; \
             if test ! -r Makefile && test -x ./configure; then \
               sync && echo "configuring in ${subdir}"; \
-              ./configure --disable-werror --enable-silent-rules --disable-option-checking CFLAGS="-w" || stat -t ./configure; \
+              ./configure --disable-werror --enable-silent-rules \
+                --disable-option-checking CFLAGS="-w" || stat -t ./configure; \
             elif test ! -e Makefile && test -x ./config.status; then \
               sync && echo "checking with ./config.status in ${subdir}"; \
               ./config.status CFLAGS="-w" || stat -t ./config.status; \
@@ -512,7 +555,8 @@ jobs:
             fi
             for srcfile in *.c; do \
               sync && echo "attempting to use $(which make) to compile ${srcfile} in ${subdir}"; \
-              make "$(echo "${srcfile}" | sed "s/\.c/.o/g")" V=0 CFLAGS="-w" || stat -t "${srcfile}"; \
+              make "$(echo "${srcfile}" | sed "s/\.c/.o/g")" V=0 CFLAGS="-w" || \
+                stat -t "${srcfile}"; \
             done; \
             popd; \
           elif test -d "${subdir}" && (test -r "${subdir}/Makefile.in" || test -r "${subdir}/Makefile.am" || test -r "${subdir}/Makefile.def" || test -r "${subdir}/Makefile.tpl"); then \
@@ -522,7 +566,8 @@ jobs:
             sync && echo "skipping attempt to build more objfiles in ${subdir}"; \
           fi; \
         done
-        (time (find . -name '*.o' -exec cp -v {} . ";")) || echo "failed copying an object file"
+        (time (find . -name '*.o' -exec cp -v {} . ";")) || \
+          echo "failed copying an object file"
 
     - name: Extra coverage build (C), part 2
       if: matrix.language == 'c-cpp' && success()
@@ -550,10 +595,15 @@ jobs:
           cfiledir="$(dirname "${cfile}")"; \
           if test ! -e "${cobjfile}"; then \
             echo "${CC} -c -w -Wno-error -Wfatal-errors ${FINAL_CPPFLAGS} -I\"${cfiledir}\" -iquote \"${cfiledir}\" -I\"${cfiledir}\"/.. -iquote \"${cfiledir}\"/.. ${cfile}"; \
-            ${CC} -c -w -Wno-error -Wfatal-errors ${FINAL_CPPFLAGS} -I"${cfiledir}" -iquote "${cfiledir}" -I"${cfiledir}"/.. -iquote "${cfiledir}"/.. ${cfile} || stat -t "${cfile}" || echo "cfile is ${cfile}"; \
+            ${CC} -c -w -Wno-error -Wfatal-errors ${FINAL_CPPFLAGS} -I"${cfiledir}" -iquote "${cfiledir}" -I"${cfiledir}"/.. -iquote "${cfiledir}"/.. ${cfile} || \
+              stat -t "${cfile}" || echo "cfile is ${cfile}"; \
           else \
             sync && echo "objfile ${cobjfile} already exists for ${cfile}."; \
-            cp -v "${cobjfile}" "${cfiledir}" || cp -v "${cobjfile}" . || cp -v "${cobjfile}" .. || (if test -d /tmp && test -w /tmp; then cp -v "${cobjfile}" /tmp; fi) || stat -t "${cobjfile}"; \
+            cp -v "${cobjfile}" "${cfiledir}" || cp -v "${cobjfile}" . || \
+              cp -v "${cobjfile}" .. || \
+              (if test -d /tmp && test -w /tmp; then \
+                 cp -v "${cobjfile}" /tmp; fi) || \
+              stat -t "${cobjfile}"; \
           fi; \
         done
         sync && echo "done with the \"Extra coverage build (C) part 2\" step"
@@ -610,7 +660,11 @@ jobs:
         # shellcheck disable=SC2044
         for ccfile in $(find . -name '*.cc' -type f); do \
           sync && echo "One last attempt at compiling ${ccfile}..."; \
-          (test -x "$(which sccache)" && sccache g++ -c "${ccfile}") || g++ -c -Wfatal-errors "${ccfile}" || g++ -c -w -Wfatal-errors -I. "${ccfile}" || g++ -c -w -Wno-error -Wfatal-errors -fpermissive -I. -I.. "${ccfile}" || stat -t "${ccfile}"; \
+          (test -x "$(which sccache)" && sccache g++ -c "${ccfile}") || \
+            g++ -c -Wfatal-errors "${ccfile}" || \
+            g++ -c -w -Wfatal-errors -I. "${ccfile}" || \
+            g++ -c -w -Wno-error -Wfatal-errors -fpermissive -I. -I.. "${ccfile}" || \
+            stat -t "${ccfile}"; \
         done
         if test -e gdb/testsuite/gdb.apple/Makefile; then \
           pushd gdb/testsuite/gdb.apple; \
@@ -627,7 +681,11 @@ jobs:
         # shellcheck disable=SC2044
         for cppfile in $(find . -name '*.cpp' -type f); do \
           sync && echo "One last attempt at compiling ${cppfile}..."; \
-          (test -x "$(which sccache)" && sccache g++ -c "${cppfile}") || g++ -c -Wfatal-errors "${cppfile}" || g++ -c -w -Wfatal-errors -I. "${cppfile}" || g++ -c -w -Wno-error -Wfatal-errors -fpermissive -I. -I.. "${cppfile}" || stat -t "${cppfile}"; \
+          (test -x "$(which sccache)" && sccache g++ -c "${cppfile}") || \
+            g++ -c -Wfatal-errors "${cppfile}" || \
+            g++ -c -w -Wfatal-errors -I. "${cppfile}" || \
+            g++ -c -w -Wno-error -Wfatal-errors -fpermissive -I. -I.. "${cppfile}" || \
+            stat -t "${cppfile}"; \
         done
         if test -e gdb/testsuite/gdb.base/Makefile && test -e gdb/testsuite/gdb.base/langs2.cxx; then \
           pushd gdb/testsuite/gdb.base; \
@@ -643,12 +701,18 @@ jobs:
         # shellcheck disable=SC2044
         for cxxfile in $(find . -name '*.cxx' -type f); do \
           sync && echo "One last attempt at compiling ${cxxfile}..."; \
-          (test -x "$(which sccache)" && sccache g++ -c "${cxxfile}") || g++ -c -Wfatal-errors "${cxxfile}" || g++ -c -w -Wfatal-errors -I. "${cxxfile}" || g++ -c -w -Wno-error -Wfatal-errors -fpermissive -I. -I.. "${cxxfile}" || stat -t "${cxxfile}"; \
+          (test -x "$(which sccache)" && sccache g++ -c "${cxxfile}") || \
+            g++ -c -Wfatal-errors "${cxxfile}" || \
+            g++ -c -w -Wfatal-errors -I. "${cxxfile}" || \
+            g++ -c -w -Wno-error -Wfatal-errors -fpermissive -I. -I.. "${cxxfile}" || \
+            stat -t "${cxxfile}"; \
         done
         if test -e mmalloc/Makefile; then \
           pushd mmalloc; \
           sync && echo "One last attempt at compiling mmallocplusplus.cp..."; \
-          make mmallocplusplus.o || (test -x "$(which sccache)" && sccache g++ -c mmallocplusplus.cp) || g++ -c mmallocplusplus.cp || stat -t mmallocplusplus.cp; \
+          make mmallocplusplus.o || \
+            (test -x "$(which sccache)" && sccache g++ -c mmallocplusplus.cp) || \
+            g++ -c mmallocplusplus.cp || stat -t mmallocplusplus.cp; \
           cp -v ./*.o .. || ls ./*.o || pwd; \
           popd; \
         elif test -d mmalloc; then \
@@ -661,7 +725,11 @@ jobs:
       if: matrix.language == 'java-kotlin' && success()
       run: |
         pushd src/zlib/contrib/java/jzlib-1.1.2 || exit
-        mvn test || mvn test-compile || mvn generate-test-sources || mvn process-test-sources || mvn generate-test-resources || mvn process-test-resources || mvn process-test-classes || mvn pre-integration-test || mvn integration-test || mvn post-integration-test || mvn verify || stat pom.xml
+        mvn test || mvn test-compile || mvn generate-test-sources || \
+          mvn process-test-sources || mvn generate-test-resources || \
+          mvn process-test-resources || mvn process-test-classes || \
+          mvn pre-integration-test || mvn integration-test || \
+          mvn post-integration-test || mvn verify || stat pom.xml
         popd
         # shellcheck disable=SC2044
         for javafile in $(find . -name '*.java' -type f); do \
@@ -669,7 +737,9 @@ jobs:
           javac "${javafile}" || stat "${javafile}"; \
         done
         if test -n "${javafile}"; then unset javafile; fi
-        which -a ktlint || (test -x "$(which locate)" && locate ktlint) || (test -x "$(which find)" && find / -name ktlint -perm +r -user "$(whoami)" 2>/dev/null) || (sync && echo "ktlint missing")
+        which -a ktlint || (test -x "$(which locate)" && locate ktlint) || \
+          (test -x "$(which find)" && find / -name ktlint -perm +r -user "$(whoami)" 2>/dev/null) || \
+          (sync && echo "ktlint missing")
         # shellcheck disable=SC2044
         if test -x "$(which kotlin)"; then \
           sync && echo "Time for kotlin (that is, $(which kotlin))..."; \
@@ -691,7 +761,9 @@ jobs:
             if test -e ${subdir}/Makefile; then \
               pushd "${subdir}"; \
               for srcfile in *.c; do \
-                make "$(echo "${srcfile}" | sed "s/\.c/.plist/g")" || clang --analyze -w -Wno-error -Wfatal-errors -I. -I.. "${srcfile}" || stat -t "${srcfile}" || wc -l "${srcfile}"; \
+                make "$(echo "${srcfile}" | sed "s/\.c/.plist/g")" || \
+                  clang --analyze -w -Wno-error -Wfatal-errors -I. -I.. "${srcfile}" || \
+                  stat -t "${srcfile}" || wc -l "${srcfile}"; \
               done; \
               popd; \
             elif test -d "${subdir}"; then \
