trying to silence some CodeQL warnings
Change-Id: Ia6a9b3c34e317c91698848d0e685a88573004480

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -183,6 +183,13 @@ jobs:
         test -e ./.profile_generic && source ./.profile_generic && (env | uniq | sort | uniq)
         if test -x "$(which sccache)"; then \
           ./configure --enable-silent-rules CC="sccache gcc" CXX="sccache g++"; \
+          sync && stat -t src && sync; \
+          if test -z "${CC}"; then \
+            export CC="sccache gcc"; \
+          fi; \
+          if test -z "${CXX}"; then \
+            export CXX="sccache g++"; \
+          fi; \
         else \
           ./configure --enable-silent-rules; \
         fi
@@ -191,13 +198,6 @@ jobs:
         if test -x "$(which sccache)"; then \
           ./configure --disable-werror --enable-silent-rules --disable-cgen-maint CC="sccache gcc" CXX="sccache g++"; \
           make configure-bfd V=0 CC="sccache gcc" CXX="sccache g++"; \
-          sync && stat -t bfd && sync; \
-          if test -z "${CC}"; then \
-            export CC="sccache gcc"; \
-          fi; \
-          if test -z "${CXX}"; then \
-            export CXX="sccache g++"; \
-          fi; \
         else \
           ./configure --disable-werror --enable-silent-rules --disable-cgen-maint; \
           make configure-bfd V=0; \
@@ -325,12 +325,13 @@ jobs:
       if: matrix.language == 'c-cpp' && success()
       run: |
         cd src
-        if test -x "$(which sccache)"; then \
-          if test -z "${CC}"; then \
+        if test -z "${CC}"; then \
+          if test -x "$(which sccache)"; then\
             export CC="sccache gcc"; \
-          fi; \
-          if test -z "${CXX}"; then \
-            export CXX="sccache g++"; \
+          elif test -x "$(which ccache)"; then\
+            export CC="ccache gcc"; \
+          else \
+            export CC="cc"; \
           fi; \
         fi
         FINAL_CPPFLAGS="-I."
@@ -345,8 +346,8 @@ jobs:
           cobjfile="$(echo "${cfile}" | sed "s/\.c/.o/g")"; \
           cfiledir="$(dirname "${cfile}")"; \
           if test ! -e "${cobjfile}"; then \
-            echo "gcc -c -w -Wno-error -Wfatal-errors ${FINAL_CPPFLAGS} -I\"${cfiledir}\" -iquote \"${cfiledir}\" -I\"${cfiledir}\"/.. -iquote \"${cfiledir}\"/.. ${cfile}"; \
-            gcc -c -w -Wno-error -Wfatal-errors ${FINAL_CPPFLAGS} -I"${cfiledir}" -iquote "${cfiledir}" -I"${cfiledir}"/.. -iquote "${cfiledir}"/.. ${cfile} || stat -t "${cfile}" || echo "cfile is ${cfile}"; \
+            echo "${CC} -c -w -Wno-error -Wfatal-errors ${FINAL_CPPFLAGS} -I\"${cfiledir}\" -iquote \"${cfiledir}\" -I\"${cfiledir}\"/.. -iquote \"${cfiledir}\"/.. ${cfile}"; \
+            "${CC}" -c -w -Wno-error -Wfatal-errors ${FINAL_CPPFLAGS} -I"${cfiledir}" -iquote "${cfiledir}" -I"${cfiledir}"/.. -iquote "${cfiledir}"/.. ${cfile} || stat -t "${cfile}" || echo "cfile is ${cfile}"; \
           else \
             sync && echo "object file ${cobjfile} already exists for ${cfile}."; \
             cp -v "${cobjfile}" "${cfiledir}" || cp -v "${cobjfile}" . || cp -v "${cobjfile}" .. || (if test -d /tmp && test -w /tmp; then cp -v "${cobjfile}" /tmp; fi) || stat -t "${cobjfile}"; \
